---
title: "DeanRossano_ggplot2_time_series_plotting"
author: "Dean Rossano"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
crime = read_rds("Crime3years.rds") %>%
  # filter dates before 2018
  filter(Date>=date("2018-01-01")) %>% 
  # filter dates after 2019
  filter(Date<date("2020-01-01"))

# plot hourly data
hourly_crime_plot = ggplot(crime, aes(x=Date, y = Battery)) +
  scale_x_datetime(date_labels = "%m/%d/%Y-%H") +
  geom_point() +
  geom_line()

hourly_crime_plot

# create new columns for hour, weekday, month, year and weeknum
crime_new <- crime %>% 
  mutate(hour = hour(crime$Date), week = weekdays(crime$Date),
         month = month(crime$Date), year = year(crime$Date)) %>% 
  mutate(weeknum = strftime(Date, format = '%V'))

# integrate date into a weekly scale
crime_weekly <- crime_new %>% 
  group_by(weeknum, year) %>% 
  summarize(case_weekly = sum(Battery)) %>% 
  mutate(date=as.Date(paste(year, weeknum, 1, sep="-"), "%Y-%U-%u"))
# plot the weekly data
weekly_crime_plot = ggplot(crime_weekly, aes(x=date, y = case_weekly, group = 1)) +
  scale_x_date(date_labels = "%Y-%W") +
  geom_point() +
  geom_line()

weekly_crime_plot

# integrate date into a weekly scale
crime_monthly <- crime_new %>% 
  group_by(month, year) %>% 
  summarize(case_monthly = sum(Battery)) %>% 
  mutate(yearmonth=paste0(year,month)) %>% 
    mutate(date=as.Date(paste(year, month, 1, sep="-"), "%Y-%m-%d"))

# plot the weekly data
monthly_crime_plot = ggplot(crime_monthly, aes(x=date, y = case_monthly, group = 1)) +
    scale_x_date(date_labels = "%Y-%M") +
  geom_point() +
  geom_line()

monthly_crime_plot

# add a day placeholder for the stacked plot
crime_monthly_2years1 = crime_monthly %>% mutate(day=1) %>% 
  mutate(MDAY=as.Date(paste(day,month,sep="."),"%d.%m"))

# plot the stacked plot
stacked_crime_plot = ggplot(crime_monthly_2years1, aes(x=MDAY, y = case_monthly, color=as.factor(year))) +
geom_point() +
geom_line()

stacked_crime_plot
```

